trash_control/urls.py
from django.conf.urls import url
from . import views


app_name = 'trash_control'

urlpatterns = [
    url(r'^$', view=views.home_page, name='home_page'),
    url(r'^trashes/$', views.trashes_view, name='trashes_view'),
    url(r'^trashes/administration/$', views.trash_administration, name='trash_administration'),
    url(r'^trashes/(?P<trash_id>[0-9]+)/$', views.trash_detail, name='trash_detail'),
    url(r'^trashes/(?P<trash_id>[0-9]+)/trash_statistic$', views.trash_statistic, name='trash_statistic'),
    url(r'^trashes/(?P<trash_id>[0-9]+)/create_recovery_task/$', views.create_recovery_task,
        name='create_recovery_task'),
    url(r'^trashes/(?P<trash_id>[0-9]+)/create_clear_task/$', views.create_clear_task,
        name='create_clear_task'),
    url(r'^trashes/(?P<trash_id>[0-9]+)/create_remove_task/$', views.create_remove_task,
        name='create_remove_task'),
    url(r'^trashes/(?P<trash_id>[0-9]+)/clear_task_detail/(?P<clear_task_id>[0-9]+)/$',
        views.clear_task_detail, name='clear_task_detail'),
    url(r'^trashes/(?P<trash_id>[0-9]+)/remove_task_detail/(?P<remove_task_id>[0-9]+)/$',
        views.remove_task_detail, name='remove_task_detail'),
    url(r'^trashes/(?P<trash_id>[0-9]+)/recovery_task_detail/(?P<recovery_task_id>[0-9]+)/$',
        views.recovery_task_detail, name='recovery_task_detail')
]

trashsite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from . import views

urlpatterns = [
    url(r'^$', view=views.home_page, name='home_page'),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^trash_control/', view=include('trash_control.urls'), name='trash_control'),
]

trash_control/forms.py
from django import forms
from models import ClearTask, RemoveTask, RecoveryTask, Trash, models
import os


class TrashForm(forms.ModelForm):
    class Meta:
        model = Trash
        fields = ['path', 'name', 'max_trash_size']
        labels = {'path': 'Trash path', 'name': 'Trash name', 'max_trash_size': 'Max trash size'}

    def clean_path(self):
        path = self.cleaned_data['path']
        if not os.path.exists(path):
            raise forms.ValidationError("Not found path!")
        return path

    def clean_max_trash_size(self):
        if self.cleaned_data['max_trash_size'] <= 0:
            raise forms.ValidationError("Trash size can not be less than zero!")
        else:
            return self.cleaned_data['max_trash_size']

    def clean(self):
        super(TrashForm, self).clean()
        path = self.cleaned_data['path']
        name = self.cleaned_data['name']
        if os.path.exists(os.path.join(path, name)):
            raise forms.ValidationError("Folder by this path exists! Write new folder name!")


class RecoveryTaskForm(forms.ModelForm):
    names = forms.CharField(widget=forms.Textarea, max_length=200, label='Names for recovering',
                            help_text="Enter names for recovering. Each name from new line")

    class Meta:
        model = RecoveryTask
        fields = ['force']
        labels = {'force': 'Force mode:'}

    """def clean(self):
        super(RecoveryTaskForm, self).clean()
        file_or_dir_name = self.cleaned_data['file_or_dir_name']
        trash = self.cleaned_data['trash']
        if not trash.removedobject_set.all().filter(cur_name=file_or_dir_name):
            raise forms.ValidationError("Not found file or directory with this name!")"""


class ClearTaskForm(forms.ModelForm):
    class Meta:
        model = ClearTask
        fields = ['policy', 'force', 'max_amount', 'days']
        labels = {'policy': 'Clear policy:', 'force': 'Force mode:',
                  'max_amount': 'Size for file or directory', 'days': 'Count of days'}

    def clean_max_amount(self):
        if self.cleaned_data['max_amount'] <= 0:
            raise forms.ValidationError("Max file or directory size can not be less than zero!")
        else:
            return self.cleaned_data['max_amount']

    def clean_days(self):
        if self.cleaned_data['days'] <= 0:
            raise forms.ValidationError("Days count can not be less than zero!")
        else:
            return self.cleaned_data['days']


class RemoveTaskForm(forms.ModelForm):
    paths = forms.CharField(widget=forms.Textarea, max_length=300, label='Paths of removing',
                            help_text="Enter paths for removing. Each path from new line")

    class Meta:
        model = RemoveTask
        fields = ['mode', 'force', 'reg_expression']
        labels = {'force': 'Force mode:', 'mode': 'Mode of removing'}

    def clean_paths(self):
        paths = self.cleaned_data['paths']
        for path in paths.split('\n'):
            abs_path = os.path.abspath(path.replace('\r', ''))
            if not os.path.exists(abs_path):
                raise forms.ValidationError("Not found file or directory with this path : {path}".format(path=path))
        return paths

trash_control/views.py
# -*- coding: utf-8 -*-
import datetime
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .with_models_work import *
from .models import Trash, ClearTask, RemoveTask, RecoveryTask
from forms import TrashForm, RecoveryTaskForm, ClearTaskForm, RemoveTaskForm


def clear_task_detail(request, trash_id, clear_task_id):
    clear_task = get_object_or_404(ClearTask, pk=clear_task_id)
    trash = get_object_or_404(Trash, pk=trash_id)
    context = get_trash_context(trash)
    context['clear_task'] = clear_task
    return render(request, 'trash_control/clear_task_detail.html', context)


def remove_task_detail(request, trash_id, remove_task_id):
    remove_task = get_object_or_404(RemoveTask, pk=remove_task_id)
    trash = get_object_or_404(Trash, pk=trash_id)
    context = get_trash_context(trash)
    context['remove_task'] = remove_task
    return render(request, 'trash_control/remove_task_detail.html', context)


def recovery_task_detail(request, trash_id, recovery_task_id):
    recovery_task = get_object_or_404(RecoveryTask, pk=recovery_task_id)
    trash = get_object_or_404(Trash, pk=trash_id)
    context = get_trash_context(trash)
    context['recovery_task'] = recovery_task
    return render(request, 'trash_control/recovery_task_detail.html', context)


def create_remove_task(request, trash_id):
    if request.method == "GET":
        if request.GET.get("create_remove_task"):
            remove_task_form = RemoveTaskForm()
            return render(request, 'trash_control/create_remove_task.html', {'form': remove_task_form,
                                                                             'trash_id': trash_id})
    if request.method == "POST":
        if request.POST.get("create_remove_task"):
            remove_task_form = RemoveTaskForm(request.POST)
            result = ""
            if remove_task_form.is_valid():
                trash = Trash.objects.get(id=trash_id)
                data = remove_task_form.cleaned_data
                create_new_remove_task(trash, data)
                remove_task_form = RemoveTaskForm()
                result = 'Task was successfully created'
            return render(request, 'trash_control/create_remove_task.html',
                          {'form': remove_task_form, 'trash_id': trash_id, 'result': result})


def create_clear_task(request, trash_id):
    if request.method == "GET":
        if request.GET.get("create_clear_task"):
            clear_task_form = ClearTaskForm()
            return render(request, 'trash_control/create_clear_task.html', {'form': clear_task_form,
                                                                            'trash_id': trash_id})
    if request.method == "POST":
        if request.POST.get("create_clear_task"):
            clear_task_form = ClearTaskForm(request.POST)
            result = ""
            if clear_task_form.is_valid():
                trash = get_object_or_404(Trash, pk=trash_id)
                data = clear_task_form.cleaned_data
                create_new_clear_task(trash, data)
                clear_task_form = ClearTaskForm()
                result = 'Task was successfully created'
            return render(request, 'trash_control/create_clear_task.html',
                          {'form': clear_task_form, 'trash_id': trash_id, 'result': result})


def create_recovery_task(request, trash_id):
    if request.method == "GET":
        if request.GET.get("create_recovery_task"):
            recovery_task_form = RecoveryTaskForm()
            return render(request, 'trash_control/create_recovery_task.html', {'form': recovery_task_form,
                                                                               'trash_id': trash_id})
    if request.method == "POST":
        if request.POST.get("create_recovery_task"):
            recovery_task_form = RecoveryTaskForm(request.POST)
            result = ""
            if recovery_task_form.is_valid():
                trash = get_object_or_404(Trash, pk=trash_id)
                data = recovery_task_form.cleaned_data
                create_new_rec_task(trash, data)
                recovery_task_form = RecoveryTaskForm()
                result = 'Task was successfully created'
            return render(request, 'trash_control/create_recovery_task.html',
                          {'form': recovery_task_form, 'trash_id': trash_id, 'result': result})


def trash_administration(request):
    trashes_list = Trash.objects.all()
    context = {
        'trashes_list': trashes_list,
    }
    if request.method == "GET":
        if request.GET.get("del"):
            context["title"] = "Trash delete panel."
            return render(request, 'trash_control/trash_delete.html', context)
        elif request.GET.get("create"):
            trash_form = TrashForm
            context['trash_form'] = trash_form
            context['title'] = "Trash create panel."
            return render(request, 'trash_control/trash_create.html', context)

    if request.method == "POST":
        if request.POST.get("deleted_trash"):
            delete_trash(request.POST["deleted_trash"])
        elif request.POST.get("created_trash"):
            trash_form = TrashForm(request.POST)
            context['trash_form'] = trash_form
            if trash_form.is_valid():
                data = trash_form.cleaned_data
                create_new_trash(data["name"], data["path"], data["max_trash_size"])
            else:
                context["title"] = "Error by trash creating. Data is not valid. Try again!"
                return render(request, 'trash_control/trash_create.html', context)
    return HttpResponseRedirect(reverse('trash_control:trashes_view'))
    # revers - access by URL by name. Can be set other args or kwargs


def trashes_view(request):
    trashes_list = Trash.objects.all()
    context = {
        'trashes_list': trashes_list,
    }
    return render(request, 'trash_control/trashes_view.html', context)


def trash_statistic(request, trash_id):
    if request.GET.get('trash_statistic'):
        trash = Trash.objects.get(id=trash_id)
        statistics = trash.taskstatisticobject_set.all()
        context = {'statistics': statistics, 'trash': trash}
        return render(request, 'trash_control/trash_statistic.html', context)


def trash_detail(request, trash_id):
    trash = get_object_or_404(Trash, pk=trash_id)
    context = get_trash_context(trash)
    if request.method == 'POST':
        _handle_post_request_for_trash_detail(request=request, trash=trash)
    context['content'] = trash.content.keys
    return render(request, 'trash_control/trash_detail.html', context)


def _handle_post_request_for_trash_detail(request, trash):
    if request.POST.get("clear_task_del"):
        delete_clear_task(trash)
    elif request.POST.get("recovery_task_del"):
        delete_recovery_task(trash)
    elif request.POST.get("remove_task_del"):
        delete_remove_task(trash)
    elif request.POST.get("clear_task_run"):
        clear_task_list = trash.cleartask_set.all()
        if len(clear_task_list) > 0:
            clear_task = clear_task_list[0]
            clear_task.run()
            clear_task.delete()
    elif request.POST.get("recovery_task_run"):
        recovery_task_list = trash.recoverytask_set.all()
        if len(recovery_task_list) > 0:
            recovery_task = recovery_task_list[0]
            recovery_task.run()
            recovery_task.delete()
    elif request.POST.get("remove_task_run"):
        remove_task_list = trash.removetask_set.all()
        if len(remove_task_list) > 0:
            remove_task = remove_task_list[0]
            remove_task.run()
            remove_task.delete()


def home_page(request):
    now = datetime.datetime.now()
    title = 'Home page. For trash view write correct url address!'
    return render(request, 'trash_control/home_page.html', {'current_date': now, 'title': title})

trash_control/templates/trash_control/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'trash_control/trash_control_style.css' %}" />
        <style>
            ul.nav{
                margin-left: 0px;
                padding-left: 0px;
                list-style: none;
            }
            .nav li {
                display: inline;
            }
            ul.nav a {
                display: inline-block;
                width: 6em;
                padding:10px;
                border: 1px dashed #333;
                text-decoration: none;
                color: #aacc11;
                text-align: center;
            }
            ul.nav a:hover{
                background-color: green;
                color: white;
            }
        </style>
    </head>
    <body>
        <ul class="nav">
            <li><a href="{% url 'trash_control:home_page' %}">Home page</a></li>
            <li><a href="{% url 'trash_control:trashes_view' %}">All trashes</a></li>
            <li><a href="#">Contacts</a></li>
            <li><a href="#">About site</a></li>
        </ul>
        {% block content %}
        {% endblock %}
    </body>
</html>

trash_control/templates/trash_control/clear_task_detail.html
{% extends "./trash_detail.html" %}

{% block clear_task_detail %}
    <table>
        <thead>
            <th>Task of clearing</th><th></th>
        </thead>
        <tbody>
            <tr>
                <td>TRASH</td>
                <td>{{ clear_task.trash.name }}</td>
            </tr>
            <tr>
                <td>POLICY</td>
                <td>{{ clear_task.policy }}</td>
            </tr>
            <tr>
                <td>DATE OF CREATING</td><td>{{ clear_task.creating_date }}</td>
            </tr>
            <tr>
                <td>FORCE</td>
                <td>{{ clear_task.force }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}

trash_control/templates/trash_control/create_clear_task.html
{% extends "./base.html" %}

{% block title %}
    create recovery task
{% endblock %}

{% block content %}
    <h2>New clear task</h2>
    <form action="" method="post">
        {% csrf_token %}
        <fieldset>
            <table>
                {{ form.as_table }}
            </table>
            <p><input type="submit" name="create_clear_task" value="create task"></p>
        </fieldset>
    </form>
    {% if result %}
        <h4>{{ result }}</h4>
    {% endif %}
{% endblock %}

trash_control/templates/trash_control/create_recovery_task.html
{% extends "./base.html" %}

{% block title %}
    create recovery task
{% endblock %}

{% block content %}
    <h2>New recovery task</h2>
    <form action="" method="post">
        {% csrf_token %}
        <fieldset>
            <table>
                {{ form.as_table }}
            </table>
            <p><input type="submit" name="create_recovery_task" value="create task"></p>
        </fieldset>
    </form>
    {% if result %}
        <h4>{{ result }}</h4>
    {% endif %}
{% endblock %}

trash_control/templates/trash_control/create_remove_task.html
{% extends "./base.html" %}

{% block title %}
    create remove task
{% endblock %}

{% block content %}
    <h2>New remove task</h2>
    <form action="" method="post">
        {% csrf_token %}
        <fieldset>
            <table>
                {{ form.as_table }}
            </table>
            <p><input type="submit" name="create_remove_task" value="create task"></p>
        </fieldset>
    </form>
    {% if result %}
        <h4>{{ result }}</h4>
    {% endif %}
{% endblock %}

trash_control/templates/trash_control/home_page.html
{% extends "./base.html" %}
{% block title %}
home page
{% endblock %}

{% block content %}
    <div class="container">
        <p><h3>Yesterday {{ current_date }}.</h3></p>
        <h1>Hello, User!</h1>
        <p>This is the web interface of the utility 'SmartRM', which supports the:
            <ul>
                <li> View known trashes (list, separate trash in detail).</li>
                <li> Creation, control, display status and delete trashes.</li>
                <li> View tasks (list, individual task in detail).</li>
                <li> Creation, control and display the status of tasks.</li>
            </ul>
        </p>
    </div>
        <p><a href="{% url 'trash_control:trash_administration' %}" role="button">Begin work? &raquo;</a></p>
        {% load staticfiles %}
        <img src="{% static 'trash_control/trash_control_home_img.jpg' %}"
             alt='error 404' width='100%' align='middle'>
{% endblock %}

trash_control/templates/trash_control/recovery_task_detail.html
{% extends "./trash_detail.html" %}

{% block recovery_task_detail %}
    <table>
        <thead>
            <th>Task of recovering</th><th></th>
        </thead>
        <tbody>
            <tr>
                <td>TRASH</td>
                <td>{{ recovery_task.trash.name }}</td>
            </tr>
            <tr>
                <td>FILE AND DIRECTORY NAMES</td>
                <td>
                    {% for name in recovery_task.namesforrecoverytask_set.all %}
                    <p>{{ name }}</p>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <td>DATE OF CREATING</td>
                <td>{{ recovery_task.creating_date }}</td>
            </tr>
            <tr>
                <td>FORCE</td>
                <td>{{ recovery_task.force }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}

trash_control/templates/trash_control/remove_task_detail.html
{% extends "./trash_detail.html" %}

{% block remove_task_detail %}
    <table>
        <thead>
            <th>Task of removing</th><th></th>
        </thead>
        <tbody>
            <tr>
                <td>TRASH</td>
                <td>{{ remove_task.trash.name }}</td>
            </tr>
            <tr>
                <td>MODE</td>
                <td>{{ remove_task.mode }}</td>
            </tr>
            <tr>
                <td>DATE OF CREATING</td><td>{{ remove_task.creating_date }}</td>
            </tr>
            <tr>
                <td>PATHS</td>
                <td>
                    {% for path in remove_task.pathsbyremovetask_set.all %}
                    <p>{{ path }}</p>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <td>IN PATH</td>
                <td>{{ remove_task.trash.get_trash_path }}</td>
            </tr>
            <tr>
                <td>FORCE</td>
                <td>{{ remove_task.force }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}

trash_control/templates/trash_control/trash_create.html
{% extends "./trashes_view.html" %}

{% block administration %}
    <p><h2>{{ title }}</h2></p>
    <form action="{% url 'trash_control:trash_administration' %}" method="post">
        {% csrf_token %}
        {% comment %}
        <fieldset>
            <label for="trash1"> name by new trash: </label>
            <br><input type="text" name="name" id="trash1"/></br>
            <label for="trash2"> path by new trash: </label>
            <br><input type="text" name="path" id="trash2"/></br>
        </fieldset>
        {% endcomment %}
        <fieldset>
            <table>
                {{ trash_form.as_table}}
            </table>
            <br><input name="created_trash" type="submit" value="save" /></br>
        </fieldset>

    </form>
{% endblock %}

trash_control/templates/trash_control/trash_delete.html
{% extends "./trashes_view.html" %}

{% block administration %}
<h2>{{ title }}</h2>
<form action="{% url 'trash_control:trash_administration' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {% for trash in trashes_list %}
            <input type="radio" name="deleted_trash" id="trash{{ forloop.counter }}" value="{{ trash.id }}" />
            <label for="trash{{ forloop.counter }}">{{ trash }}</label>
            <br/>
        {% endfor %}
        <br><input type="submit" value="delete" /></br>
    </fieldset>

</form>
{% endblock %}

trash_control/templates/trash_control/trash_detail.html
{% extends "./base.html" %}

{% block title %}detail trash view {{ trash.name }}{% endblock %}

{% block content %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'trash_control/modal_window_style.css' %}" />
    <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.3.min.js"></script>

    <h1>Detail view {{ trash.name }}</h1>
    <table>
        <thead>
            <th>Trash</th><th></th>
        </thead>
        <tbody>
            <tr>
                <td>NAME</td>
                <td>{{ trash.name }}</td>
            </tr>
            <tr>
                <td>PATH</td><td>{{ trash.path }}</td>
            </tr>
            <tr>
                <td>FILES COUNT</td>
                <td>{{ trash.files_count }}</td>
            </tr>
            <tr>
                <td>SIZE</td>
                <td>{{ trash.size }}</td>
            </tr>
            <tr>
                <td>LAST CLEARING</td>
                <td>{{ trash.last_clearing_date }}</td>
            </tr>
        </tbody>
    </table>

    <p/>

    <form action="{% url 'trash_control:trash_statistic' trash.id %}" method="get">
        {% csrf_token %}
        <input type="submit" value="get report" class="open_window">
        <input name="trash_statistic" type="submit" value="get statistic">
    </form>
    <p/>

    <div class="overlay" title="window"></div>
    <div class="popup">
        <div class="close_window">x</div>
        <h3>Report on the last completed task</h3>
        <p> {{ trash.report }} </p>
    </div>
    <script type="text/javascript">
        $('.popup .close_window, .overlay').click(function (){
        $('.popup, .overlay').css({'opacity': 0, 'visibility': 'hidden'});
        });

        $('input.open_window').click(function (e){
        $('.popup, .overlay').css({'opacity': 1, 'visibility': 'visible'});
        e.preventDefault();
        });

        $('a.open_window').click(function (e){
        $('.popup, .overlay').css({'opacity': 1, 'visibility': 'visible'});
        e.preventDefault();
        });
    </script><br/>

    <fieldset>
        <h4>Content:</h4>
        <ul>
            {% for obj in content %}
                <li class="content">{{ obj }}</li><br/>
            {% endfor %}
        </ul><br/>
    </fieldset>

    <fieldset>
        <h4>Clear tasks.</h4>
        <ul>
            {% for task in clear_tasks %}
                <li><a href="{% url 'trash_control:clear_task_detail' trash.id task.id%}">{{ task }}</a></li>
            {% endfor %}

            {% block clear_task_detail %}
            {% endblock %}
        </ul><br/>
        <form action="{% url 'trash_control:trash_detail' trash.id %}" method="post">
            {% csrf_token %}
            <input name="clear_task_del" type="submit" value="delete task" />
            <input name="clear_task_run" type="submit" value="run current task" />
        </form>
        <form action="{% url 'trash_control:create_clear_task' trash.id %}" method="get">
            {% csrf_token %}
            <input name="create_clear_task" type="submit" value="add new task"/>
        </form>
    </fieldset>

    <fieldset>
        <h4>Remove tasks.</h4>
        <ul>
            {% for task in remove_tasks %}
                <li><a href="{% url 'trash_control:remove_task_detail' trash.id task.id%}">{{ task }}</a></li>
            {% endfor %}

            {% block remove_task_detail %}
            {% endblock %}
        </ul><br/>
        <form action="{% url 'trash_control:trash_detail' trash.id %}" method="post">
            {% csrf_token %}
            <input name="remove_task_del" type="submit" value="delete task" />
            <input name="remove_task_run" type="submit" value="run current task" />
        </form>
        <form action="{% url 'trash_control:create_remove_task' trash.id %}" method="get">
            {% csrf_token %}
            <input name="create_remove_task" type="submit" value="add new task"/>
        </form>
    </fieldset>

    <fieldset>
        <h4>Recovery tasks.</h4>
        <ul>
            {% for task in recovery_tasks %}
                <li><a href="{% url 'trash_control:recovery_task_detail' trash.id task.id%}">{{ task }}</a></li>
            {% endfor %}

            {% block recovery_task_detail %}
            {% endblock %}
        </ul><br/>
        <form action="{% url 'trash_control:trash_detail' trash.id %}" method="post">
            {% csrf_token %}
            <input name="recovery_task_del" type="submit" value="delete task" />
            <input name="recovery_task_run" type="submit" value="run current task" />
        </form>
        <form action="{% url 'trash_control:create_recovery_task' trash.id %}" method="get">
            {% csrf_token %}
            <input name="create_recovery_task" type="submit" value="add new task"/>
        </form>
    </fieldset>
{% endblock %}

trash_control/templates/trash_control/trash_statistic.html
{% extends "./base.html" %}

{% block title %}
    trash statistic
{% endblock %}

{% block content %}
    <h2>Statistic for trash {{ trash.name }}</h2>
    <table>
        <thead>
            <th>Tasks type</th>
            <th>Tasks info</th>
            <th>Tasks result</th>
            <th>Date</th>
        </thead>
        <tbody>
            {% for statistic in statistics %}
                <tr>
                    <td>{{ statistic.type_task }}</td>
                    <td>{{ statistic.content }}</td>
                    <td>{{ statistic.result }}</td>
                    <td>{{ statistic.execution_date }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

trash_control/templates/trash_control/trashes_view.html
{% extends "./base.html" %}
    <title>trashes view</title>
{% block content %}
    <h1>All trashes</h1>
    <h4>For detail trash view click by reference.</h4>
    <ul>
        {% for trash in trashes_list %}
        <li>
            <a href="{% url 'trash_control:trash_detail' trash.id %}">{{ trash }}
            </a>
        </li>
        {% endfor %}
    </ul>
    <form action="{% url 'trash_control:trash_administration' %}" method="get">
        {% csrf_token %}
        <input name="create" type="submit" value="add new trash"/>
        <input name="del" type="submit" value="delete trash" />
    </form>
    {% block administration %}
    {% endblock %}
{% endblock %}